- platform: template
  switches:
    bedroom_light_gateway:
      turn_on:
        service: light.turn_on
        entity_id: light.bedroom_light_gateway
        data:
          color_name: cyan
          brightness_pct: 90
      turn_off:
        service: light.turn_off
        entity_id: light.bedroom_light_gateway
      friendly_name: "Bedroom Light Gateway"
      value_template: "{{ is_state('light.bedroom_light_gateway', 'on') }}"

    home_cam10_camera_switch:
      # value_template: "{{ is_state('binary_sensor.home_cam10_camera_switch', 'on') }}"
      turn_on:
        service: rest_command.int_cam10_rec_on
      turn_off:
        service: rest_command.int_cam10_rec_off    