esphome:
  name: home-gateway-ajax
  platform: ESP8266
  board: d1_mini
  
substitutions:
  node_name: "Home Gateway Ajax"
  node_id: home_gateway_ajax
  ha_notify_service: notify.notify

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${node_name} Fallback"
    password: !secret ap_password

# captive_portal:

ota:
  id: "${node_id}_ota"
  password: !secret ota_password
  
api:
  password: !secret api_password
  reboot_timeout: 10min
  encryption:
    key: !secret api_ecryption_key
    
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_pass
  ota: false

logger:
  level: INFO
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
  
sensor:
  - platform: uptime
    name: "${node_name} Uptime"
    unit_of_measurement: "days"
    accuracy_decimals: 2
    filters:
    - lambda: return x / 86400.0;
    
  - platform: wifi_signal
    name: "${node_name} WiFi"
    
  - platform: pulse_counter
    name: "${node_name} Pulse Counter"
    id: "${node_id}_pulse_counter"
    pin: D2
    update_interval: 5s
    internal_filter: 5us
    count_mode:
      rising_edge: INCREMENT
      falling_edge: INCREMENT
    internal: true
    unit_of_measurement: 'pulses/5sec'
    filters:
    - lambda: return x / 12.0;
  
binary_sensor:
  - platform: template
    name: "${node_name} Armed"
    lambda: |-
      if (id(${node_id}_pulse_counter).state > 0) {
        return true;
      } else {
        return false;
      }

