esphome:
  name: outdoor_climate
  platform: ESP8266
  board: d1_mini
  
substitutions:
  node_name: "Outdoor Climate"
  node_id: outdoor_climate
  ha_notify_service: notify.notify

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback"
    password: !secret ap_password

captive_portal:

ota:
  password: !secret ota_password

logger:
  level: INFO
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
  
web_server:
  port: 80

api:
  password: !secret api_password
  reboot_timeout: 10min
  
time:
  - platform: homeassistant
    id: time_platform
  
i2c:
  sda: D2
  scl: D1
  scan: false
  id: bus_a
  # frequency: 100kHz
